### ISSUE TITLE
intake STAC plugin?

### ISSUE THREAD

**Issue by rabernat** [intake/intake#224]
In pangeo, we are exploring the use of [Spatio Temporal Asset Catalogs](https://github.com/radiantearth/stac-spec) (STAC) for cataloging our cloud-based holdings (see https://github.com/radiantearth/stac-spec/issues/366). STAC is a language-agnostic .json spec for describing _items_, _collections_, and _catalogs_. STAC is an open-source project with broad community support from the remote sensing community. It would make a lot of sense for us to adopt some version of it as our "master" asset catalog. For us, it's important that our catalogs can be read and data loaded from any language, not just python.

However, we are quite pleased the intake user experience and would like to keep using it from the python side. What seems to be needed is some kind of STAC to intake translation layer, which would parse a STAC catalog and, with some hints, turn it into an intake catalog.

I'm wondering if anyone here has thought about STAC and how it might integrate with intake. Pinging @scottyhq and @jsignell, who have been working in this space.

**Comment by seibert** [comment]
@martindurant has implemented "catalog plugins" which adapt a different catalog system into Intake's catalog format.  (For example, automatically enumerating all tables in a database as data sources.)  I think such a catalog plugin could be created so Intake could read STAC files.

**Comment by rabernat** [comment]
@seibert - can you point to an example of a catalog plugin?

**Comment by seibert** [comment]
Hmm, perhaps I am remembering something that was prototyped, but not made official.  I do see that intake-spark subclasses `Catalog` to do this automatic population of sources, but I was thinking of something more modular.

@martindurant should chime in here and remind me what I'm thinking of.  :)

**Comment by martindurant** [comment]
Intake-sql's SQLCatalog does this, as does the unreleased intake-bluesky. I am at a clinic, can give links and details when i get back to my desk.

On January 7, 2019 10:07:15 AM EST, Stan Seibert <notifications@github.com> wrote:
>Hmm, perhaps I am remembering something that was prototyped, but not
>made official.  I do see that intake-spark subclasses `Catalog` to do
>this automatic population of sources, but I was thinking of something
>more modular.
>
>@martindurant should chime in here and remind me what I'm thinking of. 
>:)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ContinuumIO/intake/issues/224#issuecomment-451964568

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by martindurant** [comment]
Also referenced in https://github.com/pangeo-data/pangeo/issues/522 and elsewhere

I think both cases are of interest here. [SQLCatalog](https://github.com/ContinuumIO/intake-sql/blob/master/intake_sql/sql_cat.py#L7) is pretty simple, and just gets a list of known tables at instantiation or catalog refresh time, creating a SQLSource for each in the `.entries` attribute (a dictionary).

[intake-bluesky's implementation](https://github.com/danielballan/intake-bluesky/blob/master/intake_bluesky.py#L26) is somewhat more involved, and more along the lines pictured here: the class takes a query-string as input, and performs a query (on mongo) dynamically at runtime - this is done by having the `entries` attribute as a subclass of dict for lazy lookup; also, doing "search" on the catalog takes the previous query and refines it for a new instance, rather than literally search through the existing entries, so the work is pushed to mongo. 

Note that, because the catalog classes are also data sources, it makes total sense to have a "master catalog" where the entries call the searching catalog with various predetermined search-strings, and/or allow for user parameters which tune exactly what search gets done at runtime.

**Comment by martindurant** [comment]
https://github.com/pangeo-data/intake-stac
