### ISSUE TITLE
csv plugin should not use Dask

### ISSUE THREAD

**Issue by johntfoster** [intake/intake#302]
As mentioned in the comments at the top of [csv.py](https://github.com/intake/intake/blob/master/intake/source/csv.py), plugins should not use Dask directly.  There is an edge case that violates the spirit of intake as I understand it.

I am setting up a data catalog via yaml files in which I am giving the option of loading identically formatted data from two different sources.  One being a PostgresSQL database, the other a locally stored CSV file.  Because the SQL query uses Pandas `pandas.read_sql()` as a dependency which allows for passing in a *kwarg* `index_col`.  Pandas `pandas.read_csv()` also allows passing this *kwarg*; however, `dask.dataframe.read_csv` **does not** allow passing in this *kwarg*.   Therefore the dataframes cannot be indexed in the same way at load time.

If the csv driver simply used `pandas.read_csv()` instead, this would work.  As mentioned in the comments, the base class still implements `to_dask()` so this would have no negative effect.

**Comment by martindurant** [comment]
Thanks for bringing this up.
I would say that the situation is no longer as straight forward as it was at the time that comment was inserted. There is indeed an argument for calling pd.read_csv directly, because of some options which are not available in dd.read_csv, and perhaps better performance in the case of small datasets. However, there are some reasons to want to keep using the Dask version too:
- ability to load chunkwise across large files; in the case of pandas, you can only stream one file
- similarly, if you really have big data and do want dask, turning a set of pd.read_csv calls into a dask dataframe is not trivial, we would end up calling Dask anyway
- there are additional useful features coming from Dask, such as the farsing of filenames into categorical columns

I could raise an issue with Dask, as to why the `index_col` kwarg is not supported, but I should point out that attempting to do `index=` says you should use the following instead:
```
dd.read_csv(...).set_index(index_col)
```

**Comment by ian-r-rose** [comment]
Another data point on this:

I am trying to load a remote CSV from a server that, it turns out, does not support HTTP HEAD requests. The dask csv loader makes such a request by default, but the pandas one does not, and so a naive intake CSV load fails.

Now, it's probably right to say this is a problem that should be fixed upstream (either in dask, or with the admin of the server itself), but it's still a non-trivial difference between the two loaders that has resulted in some cryptic errors.

**Comment by johntfoster** [comment]
It's my understanding (or belief) that early versions of Dask did not support multi-indexed dataframes, but the current version does.  So perhaps the `dd.csv_read()` was implemented earlier and never updated.  I can open an issue with Dask to see if this can be fixed.

**Comment by martindurant** [comment]
Your point is still valid, and I am not sure on the whole what to do about it. A direct pandas approach as an alternative in the driver is certainly possible, but will, in effect, need code duplication to also handle multiple file and path-parsing cases, not to mention that `.to_dask()` should probably still be available in that case too (one file per partition).

**Comment by martindurant** [comment]
(btw, the simple workaround would be to use the caching interface to download all the source files when first accessing, and so stepping around the vagaries of HTTP file-like operations; or, of course, store on s3/gcs/...).

**Comment by bilderbuchi** [comment]
@martindurant you said:
> but I should point out that attempting to do index= says you should use the following instead:

> dd.read_csv(...).set_index(index_col)

How am I supposed to use this with Intake? I have a csv file that needs `index_col` to parse timestamps correctly, but then of course get the mentioned error and this message.

If I try to do ` source = intake.open_csv(...).set_index('time')` as this message seems to suggest(?), I get `
AttributeError: 'CSVSource' object has no attribute 'set_index'`.

Can you tell me how do I correctly set the index column? 

Why is this issue closed, btw, as afaict the OP's issue is not resolved?

**Comment by martindurant** [comment]
Data sources provide (at least) two methods for reading
- `read()`, which produces an in-memory version of the data, and
- `to_dask()` which provides a Dask object, normally lazy and possibly larger-than-memory. 
In this case, the two correspond to a Pandas dataframe and a Dask dataframe, respectively.

So, to answer your question:
```
source = intake.open_csv(...)
df = source.to_dask().set_index('time')
```

Note that the arguments to open_csv, which are passed to read_csv, can already include index and column parsing information, so you might not need two steps.

**Comment by bilderbuchi** [comment]
Ah, ok, I think I understand. 
So, iiuc, it's only "proper"/possible to set the index upon reading (not in the data source object itself, either into Dask or Pandas. I think I'll have to read up on that, thanks for the explanation.

**Comment by martindurant** [comment]
In general, you can either pass arguments to the backend reading function (these are properties of the "data source"), or you can read the data source immediately or lazily and manipulate that.\

Since this thread was originally talking about CSV, the index_col parameter would work in a single step (Dask or Pandas or even Spark, I think); but the thread also mentions SQL, which is a much trickier situation with differences between Dask and Pandas.
