### ISSUE TITLE
Pass pathlib to open_catalog

### ISSUE THREAD

**Issue by quartox** [intake/intake#314]
Was trying to pass a `pathlib.Path` to `intake.open_catalog` and got the following error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-22-ceeaa41394e2> in <module>
----> 1 cat = intake.open_catalog(cat_file)

/nas/jlord/conda/envs/intake/lib/python3.7/site-packages/intake/__init__.py in open_catalog(uri, **kwargs)
    149     if driver not in registry:
    150         raise ValueError('Unknown catalog driver (%s), supply one of: %s'
--> 151                          % (driver, list(sorted(registry))))
    152     return registry[driver](uri, **kwargs)
    153 

ValueError: Unknown catalog driver (None), supply one of: ['catalog', 'csv', 'intake_remote', 'ndzarr', 'numpy', 'spark_cat', 'spark_dataframe', 'spark_rdd', 'textfiles', 'yaml_file_cat', 'yaml_files_cat']
```

easy fix is passing `str(pathlib.Path)` but might be nice to be able to pass it directly in the future or giving a clearer error message.

**Comment by martindurant** [comment]
Interestingly weird exception, sorry. The docstring does say that it should be a str:
```
        path: str
            Location of the file to parse (can be remote)
```
Yes, Intake could do `str` to incoming paths, but that raises the obvious question, why bother using Path objects at all?

The opening of remote files is handled by the machinery in dask.bytes at the moment, and will eventually move to fsspec. Having a coherent story around Path objects there may be a good idea, but I am not quite sure how it would go.

**Comment by flutefreak7** [comment]
I use Path objects almost exclusively when dealing with paths, and they are almost universally supported by various libraries. Given that they have good support throughout the standard library now I'd say it's an good expectation that anywhere paths are accepted, the os.PathLike base class should be accepted, so that users don't have to take the extra step of converting them to a string. I'd go as far as to say that supporting pathlib.Path or os.PathLike objects is becoming an API expectation.

Sorry to pile on, but I just wanted to add a vote.

**Comment by martindurant** [comment]
Actually, fsspec does now handle Path objects, at least for local files. Probably all that needs to change the conditions [here](https://github.com/intake/intake/blob/master/intake/__init__.py#L131) **or** just cast to str before then. Happy to accept a PR.

**Comment by flutefreak7** [comment]
It's perhaps worth adding that the same bug will occur for any unexpected types because open_catalog uses isinstance, but doesn't have an else block for exception handling. For example the error that I get for supplying a Path object:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-75-97381333babe> in <module>
----> 1 mlas_cat = open_catalog(catalog_file)

c:\python37\lib\site-packages\intake\__init__.py in open_catalog(uri, **kwargs)
    155             # empty cat
    156             driver = 'catalog'
--> 157     if '_file' not in driver:
    158         kwargs.pop('fs', None)
    159     if driver not in registry:

TypeError: argument of type 'NoneType' is not iterable
```

...would also occur if one supplied a `set`, `Series`, `np.ndarray`, generator or some other sequence type that isn't a `list` or `tuple`. That could be avoided by checking against `collections.abc.Sequence` instead.

If you want to be strict about types instead of being permissive, there should probably be an [else block here](https://github.com/intake/intake/blob/master/intake/__init__.py#L131) that raises a more helpful Exception:

            if ((isinstance(uri, str) and "*" in uri)
                    or ((isinstance(uri, (list, tuple))) and len(uri) > 1)):
                # glob string or list of files/globs
                driver = 'yaml_files_cat'
            elif isinstance(uri, (list, tuple)) and len(uri) == 1:
                uri = uri[0]
                if "*" in uri[0]:
                    # single glob string in a list
                    driver = 'yaml_files_cat'
                else:
                    # single filename in a list
                    driver = 'yaml_file_cat'
            elif isinstance(uri, str):
                # single URL
                if uri.startswith('intake:'):
                    # server
                    driver = 'intake_remote'
                else:
                    if uri.endswith(('.yml', '.yaml')):
                        driver = 'yaml_file_cat'
                    else:
                        uri = uri.rstrip('/') + '/*.y*ml'
                        driver = 'yaml_files_cat'

**Comment by martindurant** [comment]
Related: https://github.com/intake/filesystem_spec/issues/434

**Comment by martindurant** [comment]
Yes, you are quite right, @flutefreak7 , and I would well appreciate a fix and test!

**Comment by martindurant** [comment]
Indeed, I may take this chance to fix this as part of a "how to contribute to OSS" talk I am writing.
