### ISSUE TITLE
Data versioning/validation: Comparing Intake with DVC, Quilt and Great Expectations

### ISSUE THREAD

**Issue by hoangthienan95** [intake/intake#337]
Hi there,
Thanks for the great tool. Excited to be learning it and integrating it into my workflow.

I found 2 other tools that I think might integrate beautifully with Intake. Using these tools separately is OK, but it'd be great to have them all integrated in a tool like Intake to boost data versioning/documenting capability. Below I give a brief description of the tools and how I think they can be integrated to Intake.

DVC uses git to version control your data, it describes how one data or model artifact was build from another data. -> provide backward tracing/ origin of data, gives context on how the data was generated.
GH repo: https://github.com/iterative/dvc

Great expectations: provides a structured way of specifying important characteristics of the data (schema, statistics etc) and detects when the data is changed in a way that those characteristics are violated -> good for detecting change in data, either because of naturally evolving data over time or because of  human error, and prevents these errors from propagating downstream undetected (in production ML models, data analysis, reports etc).
GH repo:https://github.com/great-expectations/great_expectations

Use case: maybe we can add their "expectations" JSON as part of the structure of Intake catalog yaml file? An example is here: 
https://great-expectations.readthedocs.io/en/latest/validation.html

**Comment by martindurant** [comment]
Thanks very much for posting this. I will take a little time to mull over how integrations with Intake might look; but I would like to think that one of the great features of Intake is its flexibility, so it can communicate with a wide variety of data sources and services.

**Comment by martindurant** [comment]
### DVC

This seems to me, from the Intake standpoint, like a "caching" mechanism, i.e., references to data files in some repo, where you need an ID/URL to load from. In this sense, it is very similar to the DAT cacher, which we already have implemented.

The difference, though, and it is important, is that in this case (compared to flat files of compressed archives), you have additional metadata and access to history. Thus, any integration should allow for the history to be accessed ("get me the data at time X") and pass the metadata out to the data source created ("last updated on Y"). The implementation of caching in Intake does not do either of these things currently, including the DAT implementation, which has some similar information available. So it would be worth working on, especially if Intake is eventually too be involved in data pipelining.

Note that in the implementation of "persistence", Intake writes data about the local version of the data (when it was made, and from which original source) into a special catalog. It doesn't feel like DVC could play the part of record keeper for such operations.

### Great Expectations

We don't, at the moment, store schema/data-type information about sources, that is inferred during initial access to the data from the data itself (so it's always "correct" but unvalidated), although some data formats/services do directly provide *a priori* schema objects of some sort (e.g., parquet, avro, SQL, xarray). There is no reason such information could not be included in a catalog, or that the drivers have an alternate way to load it, and then use the independent information for validation at that initial data access stage.

Given that the data types handled by Intake are totally generic, I don't know what fraction of them would be amenable to description by Expectations. For example, arbitrary lists of text or machine learning models will not have any schema descriptions. Of course, if there is no explicit schema, then the validation step would be skipped and the old behaviour used.

I could imagine this becoming more important in the case that Intake does cause a pipeline of execution to happen (airflow/celery style), to ensure that data outputs are correct at each stage. That seems to be the main use case for Expectations. It is not expected that Intake will go in that direction in the near-term, because interfacing with an execution environment will greatly increase the complexity of what Intake is.

**Comment by mmccarty** [comment]
I like the idea of accessing the history of the data.  We had discussed the ability to detect updates to data sources using a check sum as a way to refresh data.  This would do that and provide a way to replay multiple analysis executions as the source data changes over time. 

I see that DVC also tracks code execution in an alternative git repo.  Similar ideas in [mummify](https://github.com/maxhumber/mummify).

**Comment by hoangthienan95** [comment]
Thanks so much @martindurant and @mmccarty for giving my suggestions some thought! This helps me differentiates the use cases of different tools. I agree that Great Expectations is currently focusing on columnar data, however, I think they are branching out to other data types and storing info [at the file level](https://great-expectations.readthedocs.io/en/latest/glossary.html#filedataasset). Hopefully later on it will support storing metadata on text (word counts, lines etc) and machine learning models (distribution of weights, parameters etc). This would help developers of one microservice ensure that the data coming in from other microservices are correct, without having to specify the exact versions, since I imagine that data versioning is less linear than code versioning.

**Comment by martindurant** [comment]
GE can work without the microservice component too, no? The schema spec is just JSON, after all, and the library code to do the validation can, I imagine, be called directly.

**Comment by hoangthienan95** [comment]
@martindurant I also came across the package [quilt](https://github.com/quiltdata/quilt), and it seems like it also turns data into installable packages (like intake) and put it in a versioned system (like DVC). If you seen/used it before and have some time, would you mind explaining in what use cases people would prefer Intake more than Quilt and vice versa? It'd help people who are trying to choose between packages like me. The main difference I see is that in `quilt` they register data packages in a server-side registry (Flask/ MySQL endpoint) so users would have to get that set up instead of just using `conda`

**Comment by martindurant** [comment]
Intake doesn't want to "host" your data! This is a massive difference. We want to help you access your data wherever it is, in whatever format or service it may be, and to make this all portable and sharable without the need for any special infrastructure. Actually, the easiest way to share a catalogue is to put a YAML catalog file in a accessible location (shared drive, cloud storage, github...).

Indeed, we are considering versioning systems and the ability to use the server to post data-sets remotely (files, or just prescriptions), but these are added niceties - Intake wants to allow the minimum of fuss for users to be able to load data, and then it gets out of the way so that people can get on with the job that's important to them, analysis. Everything else, such as the visual data browsers we are developing, are purely optional. We reuse components that can prove useful, such as conda, dask, pyviz, and don't reinvent everything.

**Comment by hoangthienan95** [comment]
Thanks alot @martindurant! Please keep up the good work. Changing the issue name to reflect what was discussed here
