### ISSUE TITLE
Intake Server: Run with drivers only serverside?

### ISSUE THREAD

**Issue by kaedonkers** [intake/intake#441]
Hello! 👋
A couple of us at the UK Met Office (me+@DPeterK) are kicking the tyres on `intake-server`. We really love intake and are exploring how we can make an intake-server run in a container on a cloud deployment of Pangeo and have it available to all users of a JupyterHub.

**Question (possibly a stupid one...):**
Can I request data from an intake-server (e.g. `xarray` dataset) and receive it on the client side without the requisite intake-driver in the client's environment (e.g. `intake-xarray`)?

**Done so far:**
- Intake server running in Docker, as part of K8S deployment
- Accessing catalog entries + receiving data available in the intake-server container
- Mount external storage onto the intake-server container and have intake-server serve up that catalog+data too

**Unclear to us:**
- Where exactly does that processing (file -> Python object) using the driver take place? In the intake-server or on the client side?
- Can we specify where exactly that processing takes place?
- Does the intake-driver need to be available both to the intake-server and client for any of this to work?

Thanks!

**Comment by martindurant** [comment]
When you access a data entry on a server, there are a few possible actions:
- if `direct_access` is forbidden, the target is opened by the server and data will be streamed
- the the client doesn't have an appropriate driver, the target is opened by the server and the data will be streamed
- otherwise, the client can open the entry directly and bypass the server

In order for data to be streamed, the client must still have the "container" driver appropriate for the data type in question. For dataframes, arrays and sequences, these are built into Intake, but for xarrays, it is implemented in intake_xarray.xarray_container.RemoteXarray; i.e., you *do* need intake_xarray installed, but you won't need some of the optional extras that the other xarray drivers need, such as rasterio.

**Comment by kaedonkers** [comment]
Thanks Martin, just what I needed to know! It's a shame it doesn't quite worked how we hoped, but having clarity on exactly what intake-server can do is very useful. Cheers!
