### ISSUE TITLE
open a Hdf5 file - plugin documentation issue

### ISSUE THREAD

**Issue by MarineChap** [intake/intake#473]
The documentation is unclear about this particular format. It is mentioned in the documentation, so I guess there is an existing plugin for it but I cannot find the right one in the plugin list.
Can you point me in the right direction please ? 

Also, do you think the plugin list could be improve ? It is really unclear in particular for builtin plugin to have only the name to guess what it could be used for.
-  csv, ndzarr, textfiles plugin are easy to understand.
-  numpy is unclear (only npy, npz files ?) 
-  intake_remote and yaml_file(s)_cat just mentioned like this don't give any clue on what it is for exactly. 

Thank you 
Have a good day

**Comment by danielballan** [comment]
Thanks for the useful feedback about the documentation. Always appreciated!

Do your HDF5 files have a particular layout/structure? For example, there is an intake driver for netCDF 4 files (which is an HDF5 file with a prescribed layout for the groups and data sets). That driver is packaged in intake-xarray, but there is discussion about splitting it out, in part to aid the discoverability problem that you highlighted above.

There is no “generic” intake HDF5 driver (AFAIK). Such a thing might be hard to build because HDF5 filed may contain arbitrarily nested structures, and there is no corresponding PyData/SciPy data structure; that is, a generic HDF5 file doesn’t map onto a numpy array, pandas.DataFrame or xarray.Dataset. We could return an h5.File object, though at that point intake wouldn’t be adding much value over just using h5py directly.

**Comment by martindurant** [comment]
I am sure you are right, and we can do a lot to clarify the documentation. Briefly:
- intake_remote : a catalogue read from a remote server using the Intake protocol
- yaml_file(s)_cat: a single YAML file or a collection of YAML files specifying intake data sources, forming a catalogue

> numpy is unclear (only npy, npz files ?)

Correct. In my view, these are numpy's "standard" format, but that's supposition on my part.

I agree @danielballan 's points on HDF5: it is a container format, so does not fit under one particular driver. There could be table (structured or otherwise) and an array plugins for HDF5, as there are for [FITS](https://github.com/intake/intake-astro/tree/master/intake_astro) , but in practice, the xarray [netcdf](https://intake-xarray.readthedocs.io/en/latest/api.html#intake_xarray.netcdf.NetCDFSource) plugin, which assumes more about the structure of the HDF file, seems to be covering most needs.

**Comment by MarineChap** [comment]
Thanks you both for your answer. In fact, I did not know the HDF5 format could have a particular layout from case to case. I will read more about it. And also, try the xarray netcdf plugin. 
Thanks.
