### ISSUE TITLE
Regular expressions for search method

### ISSUE THREAD

**Issue by markusritschel** [intake/intake#510]
Hello.
Just a question (or maybe a feature request, if it's not already avalable): Is it possible to use intake's search method with regular expressions?

Something like
```python
myregex = r"matchthis\d.*$"
col.search(my_key=myregex)
```
So, similar to what I would achieve with
```python
col.df[col_df['my_key'].str.contains(myregex)]
```

Cheers,
Markus

**Comment by aaronspring** [comment]
it is implemented in intake-esm, like your example code above. See https://github.com/intake/intake-esm/pull/236

**Comment by martindurant** [comment]
It would be reasonable to enhance the search method to do more complex things, such as specifying metadata keys to consider.

However, i think you are asking for a filter on the data? That would not be the place for it, since here we are considering selecting among datasets, and not to load anything except when explicitly requester by the user.

On July 2, 2020 12:17:16 PM EDT, markusritschel <notifications@github.com> wrote:
>Hello.
>Just a question (or maybe a feature request, if it's not already
>avalable): Is it possible to use intake's search method with regular
>expressions?
>
>Something like
>```
>myregex = r"matchthis\d.*$"
>col.search(my_key=myregex)
>```
>So, similar to what I would achieve with
>```
>col.df[col_df['my_key'].str.contains(myregex)]
>```
>
>Cheers,
>Markus
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/intake/intake/issues/510

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by markusritschel** [comment]
No, I was indeed looking for a regex-like filter for the keys. I.e. exactly what is discussed in the [issue](https://github.com/intake/intake-esm/pull/236), which was linked by @aaronspring.

**Comment by martindurant** [comment]
Oh, the dataframe is the set of datasource entries, got it!

On July 4, 2020 10:54:50 AM EDT, markusritschel <notifications@github.com> wrote:
>No, I was indeed looking for a regex-like filter for the keys. I.e.
>exactly what is discussed in the
>[issue](https://github.com/intake/intake-esm/pull/236), which was
>linked by @aaronspring.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/intake/intake/issues/510#issuecomment-653775420

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
