### ISSUE TITLE
No module named 'jinja2'

### ISSUE THREAD

**Issue by MeraX** [intake/intake#578]
Hi,

thanks for this awesome project helping us to easier access our widely distributed data set!

However, I got the error `ModuleNotFoundError: No module named 'jinja2'` after installing intake 0.6.1 and importing it in Python 3.6.7.

Does `jinja2` has to be included as a requirement? 
I already made this PR #577. It might help.

Best regards,
Marek

**Comment by d70-t** [comment]
In 24f737ea `jinja2` has been removed from the `requirements.txt`. But a simple `import intake` will eventually import `intake.catalog.utils` which [uses jinja2](https://github.com/intake/intake/blob/cf7f61950eb2d45b136dbcfa472f3b5b503bc63b/intake/catalog/utils.py#L10). I think `jinja2` is indeed required in order to do parameter expansion in the catalog files.

As the referenced commit came after `0.6.0`, I can confirm that this error has been introduced in `0.6.1`.

Something which might be related is, that I noticed that `to_dask()` is not working anymore since `0.6.1` if I just install `intake` and not `intake[dataframe]`. But probably this is expected behavior.

**Comment by martindurant** [comment]
Yes, I may have been over-aggressive on trimming the requirements... There is a separate discussion around making catalog entry templating optional (because of the CPU overhead), but let's just add jinja back for now.

**Comment by d70-t** [comment]
Thanks @martindurant. I'd be fine with making templating optional, but I'd expect that `import intake` will still work without the option being active :-)

**Comment by rabernat** [comment]
I just hit this same issue. I am trying to create a (private) CI environment with the command
```
pip install intake intake-xarray s3fs xarray zarr
```

But when I import intake, it complains about missing jinja2. Then I added jinja2 to the list and it complained about msgpack. Then I added msgpack and it complained about requests. Then I gave up and found this issue.

Bottom line, pip installation of intake appears to be broken because dependencies are note being installed.

**Comment by martindurant** [comment]
Hm, jinja2 is definitely in the top-level `requests.txt`.
The following does install and import:
```
> pip install intake[dataframe] intake-xarray s3fs xarray zarr jinja2
```

**Comment by martindurant** [comment]
OK so:
- I'll rerelease intake and make sure jinja is included
- add msgpack and requests to intake-xarray's deps and rerelease (previously, these were required by intake)

**Comment by martindurant** [comment]
(intake-xarray could be rewritten to only need those optionally, when a particular driver is used, but I think they are small enough to just require always)
