### ISSUE TITLE
decouple dask

### ISSUE THREAD

**Issue by martindurant** [intake/intake#702]
Since the project's inception, dask has been used internally by virtually all sources - even source.read() would actually call source.to_dask().compute() in many cases. We shouldn't be forcing dask on people and it provides no benefit for the simple case. In fact, the dask APIs don't necessarily offer all the options of the likes of pandas, xarray... . Since we have to_dask() anyway, I propose that .read() should not require dask, and dask should not be a hard dependency. If looking ahead to pyscript usage, not needing dask would be very helpful (although I suppose it runs fine with the "sync" scheduler). 

However, dask does also give extra options, typically around reading multiple files as if they were a single thing.

This would change a lot of logic. For example, CSV (and others)
- adds the path_as_pattern option which we would need to duplicate 
- would need to list files and concat multiple inputs if given a list  of paths or globstring
- _get_schema and similar would need to directly read from a file using pandas to get a guess of the schema (and not repeat this if the end output is indeed dask).

Is it worth it?

**Comment by danielballan** [comment]
I ended up on a similar trajectory with https://github.com/bluesky/tiled/blob/main/tiled/adapters/array.py and https://github.com/bluesky/tiled/blob/main/tiled/adapters/dataframe.py. In the initial implementation they used as dask array/dataframe (respectively) as their core internal representation. Now, they were an array-like or dataframe-like.

I am happy with that evolution. It is good to have the option to deliver the objects to the user as dask, but I think it is best not to bake it too deeply into the internal (in tiled's case, server-side) I/O code.

**Comment by martindurant** [comment]
Yes, I agree. Also, we maybe could consider a wider range of `to_*` methods for some common drivers like CSV, for ray, torch, others. Currently we have spark in a couple of places, pretty sure it doesn't get used. But only read() would be guaranteed to work.

**Comment by blakerosenthal** [comment]
Jumping in here because this seems interesting / like something I could do -- 
Would it make sense to use Dask + the existing `.read()` implementations under certain conditions (Dask is installed, maybe a `use-dask` flag is set), or should Dask be restricted to `.to_dask()` methods only? I can imagine users benefitting from auto-partitioned reads in simple cases, if that's what's currently happening.

**Comment by raybellwaves** [comment]
Agreed. Would be nice for intake to be flexible and work with the N dataframe libraries out there for reading csv (if users want to add them) (e.g. a minimal base CSVSource) then plugins (?) of PandasCSVSource, DaskCSVSourse (default?), PolarsCSVSource etc.

One thing (good/bad) about STAC is there's no reader so users will do dd.read_csv(STAC_OBJECT_URL.csv) or pl.read_csv(STAC_OBJECT_URL.csv)

**Comment by kthyng** [comment]
I hit this issue pretty regularly since dask doesn't allow for all the same flags as `pd.read_csv`. I would vote for `to_dask` using dask and `.read()` not using dask.

Is there a workaround for this in the meantime? I have my own DataFrame Transform but the `read` function still maps through the default and I can't use the `index_col` flags I want to use. Rearranging to not use them is not my first choice...

**Comment by martindurant** [comment]
@kthyng , @raybellwaves - have you tried this since https://github.com/intake/intake/pull/734 ?

**Comment by kthyng** [comment]
Hmm I see that this call originates within intake but actually the issue occurs in pandas, but I am not sure why it would be behaving differently now. Does something look off about this call? (I've modified it to run here but all inputs the same.)
```
storage_options = {'simplecache': {'cache_storage': '/Users/kthyng/projects/ciofs-hindcast-report/ciofs_hindcast_report/outputs/data_cache/ctd_profiles_2005_noaa', 'same_names': True}}
csv_kwargs = {'encoding': 'ISO-8859-1', 'index_col': ['date_time', 'Press'], 'parse_dates': {'date_time': [3, 4]}, 'sep': '\t', 'nrows': 10}
url = 'simplecache::https://researchworkspace.com/files/39886023/noaa_north.txt'
pd.read_csv(url, 
            storage_options=storage_options, 
            **csv_kwargs)
```

**Comment by martindurant** [comment]
Pandas does not appear to detect that this is an fsspec URL. You can persuade it by using
```
'simplecache://::https://researchworkspace.com/files/39886023/noaa_north.txt'
```
(which is equivalent)

**Comment by kthyng** [comment]
Oh excellent, that indeed seems to fix the problem. Thank you!!

**Comment by kthyng** [comment]
I just had this same issue again and needed to apply this fix (apparently I didn't update all of my sources...) so I am going to post the error so that it's easier to find next time I hit this :)

Error:
```
ValueError: storage_options passed with file object or non-fsspec file path
```

Fix (above from @martindurant):
change simplecache syntax to `'simplecache://::https://researchworkspace.com/files/39886023/noaa_north.txt'`
