### ISSUE TITLE
Driver for searchable catalog of catalogs

### ISSUE THREAD

**Issue by dougiesquire** [intake/intake#723]
I’d like to create a catalogue of intake catalogues that provides more comprehensive search capabilities than [nesting yaml files](https://intake.readthedocs.io/en/latest/catalog.html#catalog-nesting). I’m thinking of creating an intake driver for a table (e.g. csv) containing a column of yaml descriptions for each intake catalog, plus columns for other metadata associated with those catalogs that a user may like to query on. In my case, the intake catalogs are intake-esm catalogs, so additional metadata might be things like the realms/variables/frequencies contained within each catalog. The idea is that users can do a high-level query on the table to find which catalogs they may be interested in using.

e.g.
```python
import intake

# Open the table of catalogs
# The contents of meta.csv might look something like:
# 
#   | name | realm | variable | frequency | yaml
#   -- | -- | -- | -- | -- 
#   'exp0' | ['ocean']          | ['var0', 'var1', '... | ['day', 'month', '... | 'sources:\n  exp0:\n    args:\n      obj: /path/to/esmcat0.json\n    description: ''\n    driver: intake_esm.core.esm_datastore\n    metadata: {}\n'
#   'exp1' | ['atmos']          | ['var2', 'var3', '... | ['day', 'year', '...  | 'sources:\n  exp2:\n    args:\n      obj: /path/to/esmcat1.json\n    description: ''\n    driver: intake_esm.core.esm_datastore\n    metadata: {}\n'
#   'exp2' | ['ocean', 'atmos'] | ['var0', 'var2', '... | ['day', 'month', '... | 'sources:\n  exp3:\n    args:\n      obj: /path/to/esmcat2.json\n    description: ''\n    driver: intake_esm.core.esm_datastore\n    metadata: {}\n'
meta_cat = intake.open_csv_catalog(“meta.csv”)

# Return subset of entries according to query
meta_cat_subset = meta.search(variable=“var3”)

# Get the catalog(s) that match the query
cat = meta_cat_subset.to_catalog() # returns a dict when there is more than one catalog
```

Is something like this already available within intake? Is there a more sensible approach?

**Comment by martindurant** [comment]
There are indeed some other searching methods than the standard naive text one you get by default. They might call out to a third party database to do the search, for example. However, I'm not aware of one quite like you are suggesting, which sounds interesting. Two similar cases:
- you could encode those columns as metadata in a standard YAML (or create catalog _entries at runtime, with the right metadata),
- intake_stac loads similar metadata declared with different syntax, and allowing particularly for time/location range queries on items rather than catalogs; if run as a service, it might provide sectioning of the data by those bounds.

Since it appears you want to make functionality that would be specific to intake-esm lists, it might make more sense to include this as extra functionality in that repo. However, I could imagine it being more general, defining also the type (driver) of each entry.

I would suggest that `meta_cat_subset` should already be a catalog instance, same type as `meta_cat`.

**Comment by dougiesquire** [comment]
Thanks @martindurant - that's very helpful. FWIW, I've started trying to build a simple driver that suits our needs here: https://github.com/ACCESS-NRI/intake-dataframe-catalog

**Comment by dougiesquire** [comment]
I'm curious whether there's interest in me adding [`intake-dataframe-catalog`](https://github.com/ACCESS-NRI/intake-dataframe-catalog) to the [list of known intake plugins](https://intake.readthedocs.io/en/latest/plugin-directory.html).

Happy to be told no, since it's maybe slightly niche.

Example usage of `intake-dataframe-catalog` here: https://intake-dataframe-catalog.readthedocs.io/en/latest/getting_started/quickstart.html
