### ISSUE TITLE
Suggestion for posting catalog files?

### ISSUE THREAD

**Issue by kthyng** [intake/intake#811]
Hi again. I would like to host a set of publicly-available intake catalog files. Do you have specific vision for this in intake v2, or any tips or guidelines as I get started? Apologies if I missed this in the docs. I also realize it might just be really simple as yaml files but thought there might be some things to be aware of. Thanks!

**Comment by martindurant** [comment]
Intake's philosophy is, of course, not to require any server or to force users into any particular workflow. You can put a YAML version of a catalog anywhere you like, including github repos ("github://org:repo@<tag/branch>/path/file.yaml" works, for instance) or any public cloud bucket.

However, it perhaps *would* be useful to have a catalog of examples, especially given Take2. I could make a directory in an otherwise empty repo where people are encourages to PR-add yaml files, and a reader that specifically looks for these. The metadata for each could include not only the datasets, but links to docs, notebooks and other related material.

**Comment by kthyng** [comment]
Ok thanks. And I would be happy to contribute an example or two if you start a place to do so.

**Comment by martindurant** [comment]
https://github.com/intake/intake-public-datasets

**Comment by kthyng** [comment]
@martindurant I'm adding metadata to my catalogs to try to make them more self-explanatory and have road maps for people who might come along, in the direction you mentioned. For example, links to websites and notebooks with more information. However, I noticed the catalog metadata went to the bottom of the catalog which would make it unlikely for a person visually looking at the catalog to see it. I was thinking the catalog-level metadata would be how a user might be able to read and interpret the use of a catalog. Am I misunderstanding this? Should I instead expect them to look at the metadata through a reader?

**Comment by martindurant** [comment]
They keys are saved in alphabetical order :|. This is probably configurable, but the intention is not that people should read the YAML files as they are on disk. For a start, catalog definitions might come from other places than YAML files. Eventually, there should indeed be GUI and smart search available for dealing with this information; in the nearer future, I should be able to craft at least a decent HTML repr for the notebook, so that you can expand the sections you need (remembering that there is metadata associated with the whole catalog, and each data and entry). Until then, users can introspect the `.metadata` attribute(s) before choosing to use a reader.
